### PR TITLE
Image details function

### PR DESCRIPTION
**Pull request by olivia-lin**
- changed function name from image_details to get_image_details
- updated function doc string in .py file for get_image_details
- updated readme function section for all three functions

### CODE REVIEW

**Comment by jielinyu** [comment]
Great job! It is better to update Readme in master branch instead of function branch next time.

**Comment by olivia-lin** [comment]
Good catch, thanks!

**Comment by gilbertlei** [comment]
I agree with all the changes. thanks!

**Comment by gilbertlei** [comment]
@olivia-lin I noticed that, in your "test_get_image_details.py", your function documentation has no appropriate indent. pytest reports error due to this problem. please double check and modify it.

**Pull request merged**
